---
title: "MetDist Pipeline"
author: "Emmi Mueller"
date: "2025-12-16"
output: pdf_document
---

```{r setup, echo=FALSE}
rm(list=ls())

knitr::opts_chunk$set(
  fig.width = 6,
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  tidy.opts = list(width.cutoff = 60),
  tidy = TRUE)
```

```{r}
library("BiocManager")
library("vegan")
library("fitdistrplus")
library("ggplot2")
library("car")
library("actuar")
library("scales")
library("MoMAColors")
library("bbmle")
library("dplyr")
library("mgcv")
library("tidyr")
library("cowplot")
library("here")
#library("ggridges")
library("rsq")
# library("gdata")
library("ggpmisc")
# library("ggpp")
# library("ggsignif")
# library("Pareto")
# library("spatstat")
#library("aod")
# library("stats")
library("tidymv")
# library("plot3D")
# library("ggformula")
# library("DescTools")
# library("tibble")
# library("ggpubr")
library(multcompView)
library(grDevices)
library(truncnorm)

#devtools::install_github("johannesbjork/LaCroixColoR")
#library(LaCroixColoR)
#BiocManager::install("flowCore")

source("./MetDist_functions.R")
source("./mothur_tools.R")
```

```{r figure_setup}
my.cols <- RColorBrewer::brewer.pal(n = 4, name = "Greys")[3:4]

# Set theme for figures in the paper
theme_set(theme_classic() + 
  theme(axis.title = element_text(size = 16),
        axis.title.x = element_text(margin = margin(t = 15, b = 15)),
        axis.title.y = element_text(margin = margin(l = 15, r = 15)),
        axis.text = element_text(size = 13),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        #axis.line.x = element_line(linewidth = 1),
        #axis.line.y = element_line(linewidth = 1),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(linewidth = 1),
        axis.ticks.y = element_line(linewidth = 1),
        axis.ticks.length = unit(.1, "in"),
        panel.border = element_rect(color = "grey20", fill = NA, linewidth = 1.5),
        legend.text = element_text(size = 14),
        strip.text = element_text(size = 14),
        strip.background = element_blank()
        ))
```

```{r}
met_ULRG <- list(MD_ULRG_01_A, MD_ULRG_02_A, MD_ULRG_03_A, MD_ULRG_04_A, MD_ULRG_05_A, MD_ULRG_06_A, MD_ULRG_07_A, MD_ULRG_08_A, MD_ULRG_09_A, MD_ULRG_10_A, MD_ULRG_11_A, MD_ULRG_12_A, MD_ULRG_13_A, MD_ULRG_14_A, MD_ULRG_01_B, MD_ULRG_02_B, MD_ULRG_03_B, MD_ULRG_04_B, MD_ULRG_05_B, MD_ULRG_06_B, MD_ULRG_07_B, MD_ULRG_08_B, MD_ULRG_09_B, MD_ULRG_10_B, MD_ULRG_11_B, MD_ULRG_12_B, MD_ULRG_13_B, MD_ULRG_14_B)

samples_ULRG <- c("MD_UL_01_A", "MD_UL_02_A", "MD_UL_03_A", "MD_UL_04_A", "MD_UL_05_A", "MD_UL_06_A", "MD_UL_07_A", "MD_UL_08_A", "MD_UL_09_A", "MD_UL_10_A", "MD_UL_11_A", "MD_UL_12_A", "MD_UL_13_A", "MD_UL_14_A","MD_UL_01_B", "MD_UL_02_B", "MD_UL_03_B", "MD_UL_04_B", "MD_UL_05_B", "MD_UL_06_B", "MD_UL_07_B", "MD_UL_08_B", "MD_UL_09_B", "MD_UL_10_B", "MD_UL_11_B", "MD_UL_12_B", "MD_UL_13_B", "MD_UL_14_B")

MD_ULRG_G3 <- c("MD_ULRG_01_A"="UL01A_RSG.fcs", "MD_ULRG_02_A"="UL02A_RSG.fcs", "MD_ULRG_03_A"="UL03A_RSG.fcs", "MD_ULRG_04_A"="UL04A_RSG.fcs", "MD_ULRG_05_A"="UL05A_RSG.fcs", "MD_ULRG_06_A"="UL06A_RSG.fcs", "MD_ULRG_07_A"="UL07A_RSG.fcs", "MD_ULRG_08_A"="UL08A_RSG.fcs", "MD_ULRG_09_A"="UL09A_RSG.fcs", "MD_ULRG_10_A"="UL10A_RSG.fcs", "MD_ULRG_11_A"="UL11A_RSG.fcs", "MD_ULRG_12_A"="UL12A_RSG.fcs", "MD_ULRG_13_A"="UL13A_RSG.fcs", "MD_ULRG_14_A"="UL14A_RSG.fcs", "MD_ULRG_01_B"="UL01B_RSG.fcs", "MD_ULRG_02_B"="UL02B_RSG.fcs", "MD_ULRG_03_B"="UL03B_RSG.fcs", "MD_ULRG_04_B"="UL04B_RSG.fcs", "MD_ULRG_05_B"="UL05B_RSG.fcs", "MD_ULRG_06_B"="UL06B_RSG.fcs", "MD_ULRG_07_B"="UL07B_RSG.fcs", "MD_ULRG_08_B"="UL08B_RSG.fcs", "MD_ULRG_09_B"="UL09B_RSG.fcs", "MD_ULRG_10_B"="UL10B_RSG.fcs", "MD_ULRG_11_B"="UL11B_RSG.fcs", "MD_ULRG_12_B"="UL12B_RSG.fcs", "MD_ULRG_13_B"="UL13B_RSG.fcs", "MD_ULRG_14_B"="UL14B_RSG.fcs")

for(key in names(MD_ULRG_G3)){
#  assign(key, process(here("data", "MetDistRA21", "ULRG_RSG_R3Gate", MD_ULRG_G3[key]), "B530-H", TRUE))
    assign(key, process(here("data", "MetDistRA21", "ULRG_RSG_R3Gate", MD_ULRG_G3[key]), "B530-H", FALSE))
}
```

## Read in metadata and generate metadata Samples dataframe
```{r}
Samples <- read.csv(here("data","MetDistRA21", "MetDistRA21_Samples.csv"))
GSSF_G <- read.csv(here("data", "GSSF-G.csv"), header = TRUE)
Samples <- as.data.frame(BP_fxn(read.csv(here("data", "MetDistRA21", "RTLC_BP.csv"), header = FALSE), Samples, "RTLC"))
Samples <- as.data.frame(BP_fxn(read.csv(here("data", "MetDistRA21", "20210825_ULRG_SYBR_RSG_ATP", "20210825_ULRG_BP.csv"), header = FALSE), Samples, "ULRG"))
Samples <- subset(Samples, select = -c(DPM, DPMKills, molLeu, molLeuLhr, gCLhr))

Samples <- subset(Samples, Samples$Set != "EC_GC")

met_samples <- rbind(subset(Samples, Samples$Set == "RTLC"), subset(Samples, Samples$Set == "ULRG"), subset(Samples, Samples$Set == "ULRG"), subset(Samples, Samples$Set == "GSSF"))
met_samples$Sample <- samples_all
met_samples$Tau <- log((10^met_samples$Tau)/60, 10)

met_samples$Lake_rep <- c(rep(NA, 64), rep(c("A", "B", "C", "D", "E"), 10))
met_samples$Time <- c(rep(NA, 64), GSSF_G$Mins)
met_samples$Hours <- c(rep(NA, 64), GSSF_G$Mins/60)
met_samples$OD600 <- c(rep(NA, 64), GSSF_G$OD)

```

#Lnorm - all data
```{r}
metn <- 1
ln_fits <- data.frame("Sample" = NA, "Set" = NA, "RSG_ab" = NA, "qlnorm" = NA)
ln_param <- data.frame("Sample" = NA, "meanlog" = NA, "sdlog" = NA, "AIC_ln" = NA,"BIC_ln" = NA, "lL_ln" = NA, "R2_ln" = NA)
for(met1 in met_all){
  
  met_sub <- met1
  nll_ln <- function(meanlog, sdlog) {
    -sum(dlnorm((met_sub[,"RSG_ab"]), meanlog = meanlog, sdlog = sdlog, log = TRUE))
  }
  mle_fit <- mle2(
    minuslogl = nll_ln,
    start = list(meanlog = 1, sdlog = median(met_sub[,"RSG_ab"])),  # Reasonable starting values
    lower = c(0.001, 0.001),
    upper = c(Inf, Inf),
    method = "L-BFGS-B"
  )
  print(samples_all[metn])
  print(summary(mle_fit))
  
  e_cdf <- rank(met_sub[,"RSG_ab"])/length(met_sub[,"RSG_ab"])
  
  qlnorm <- qlnorm(e_cdf, meanlog = coef(mle_fit)[1], sdlog = coef(mle_fit)[2])
  
  fun_ecdf <- ecdf(met_sub[,"RSG_ab"])
  R2 <- summary(lm(fun_ecdf(met_sub[,"RSG_ab"])~ plnorm(met_sub[,"RSG_ab"], coef(mle_fit)[1], coef(mle_fit)[2])))$r.squared

  fit <- cbind(rep(samples_all[metn], length(met_sub[,"RSG_ab"])),rep(met_samples[metn, "Set"], length(met_sub[,"RSG_ab"])), met_sub, qlnorm)
  ln_param <- rbind(ln_param, data.frame("Sample" = samples_all[metn], "meanlog" = coef(mle_fit)[1], "sdlog" = coef(mle_fit)[2], "AIC_ln" = AIC(mle_fit),"BIC_ln" = 2*(log(length(met_sub[,"RSG_ab"]))) - 2*logLik(mle_fit), "lL_ln" = logLik(mle_fit), "R2_ln" = R2))
  colnames(fit) <- c("Sample", "Set", "RSG_ab", "qlnorm")
  ln_fits <- rbind(ln_fits, fit)
  
  metn <- metn + 1
}

ln_fits <- ln_fits[-1,]
ln_fits <- subset(ln_fits, ln_fits$qlnorm != "Inf")
ln_param <- ln_param[-1,]

CI <- data.frame("x_ci" = seq(0, 7, 0.5), "y_ci" = seq(0, 7, 0.5))



met_samples <- cbind(met_samples, ln_param[,c("meanlog", "sdlog", "AIC_ln", "BIC_ln", "lL_ln", "R2_ln")])

# ln_boots <- c()
# x <- 0
# while(x < 10000){
#   fits <- sample_n(ln_fits, 5000)
#   ln_boots <- c(ln_boots, summary(lm(log(fits$RSG_ab,10) ~ log(fits$qlnorm, 10)))$r.squared)
#   x <- x + 1
#   if(x%%100 == 0){
#     print(x)
#   }
# }
# 
# ln_boot_r2 <- round(mean(ln_boots),2)

CI <- data.frame("x_ci" = seq(0, 7, 0.5), "y_ci" = seq(0, 7, 0.5))

Lnorm_fit_plot <- ln_fits %>% sample_n(10000) %>%
  ggplot(aes(y = log(qlnorm, 10), x = log(RSG_ab, 10)))+
  geom_point(alpha = 0.03, pch = 4, color = cols[3])+
  geom_ribbon(data = CI, aes(x = x_ci, y = y_ci, ymin = y_ci-1, ymax = y_ci+1), fill = alpha("black", 0.1))+
  geom_abline(slope = 1, color = "black", size = 1, linetype = "dashed")+
  ylab("Predicted values")+
  xlab("Observed values")+
  ggtitle("Lognormal")+
  scale_x_continuous(labels = label_math(expr = 10^.x, format = force))+
  scale_y_continuous(labels = label_math(expr = 10^.x, format = force), breaks = c(-3,0,3,6))+
  annotate("text", x = 2.5, y = 7, label = "italic(r[plain('m')]^2)==0.91", size = 5, parse = TRUE)+
  coord_cartesian(xlim = c(2,6), ylim = c(-4, 8))

Lnorm_fit_plot


ggsave("../output/QQ_Lnorm.png", width = 3.5, height = 3.5)

```

```{r}
top20 <- c()
for(met1 in met_all){
  quantile_cutoff <- quantile(met1$RSG_ab, 0.8)
  total_activity <- sum(met1$RSG_ab)
  top20_activity <- sum(met1[met1 > quantile_cutoff])
  top20_fraction <- top20_activity/total_activity
  top20 <- c(top20, top20_fraction)
}

met_samples$top20 <- top20
```